lib/mango_web/router.ex
defmodule MangoWeb.Router do
  use MangoWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  # Frontend related plugs
  pipeline :frontend do
    plug MangoWeb.Plugs.Locale
    plug MangoWeb.Plugs.LoadCustomer
    plug MangoWeb.Plugs.FetchCart
  end

  pipeline :admin do
    plug MangoWeb.Plugs.AdminLayout
    plug MangoWeb.Plugs.LoadAdmin
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", MangoWeb do
    pipe_through [:browser, :frontend]

    get "/", PageController, :index

    get "/login", SessionController, :new
    post "/login", SessionController, :create

    get "/register", RegistrationController, :new
    post "/register", RegistrationController, :create

    get "/categories/:name", CategoryController, :show

    post "/cart", CartController, :add
    get "/cart", CartController, :show
    put "/cart", CartController, :update
  end

  # Only autenticated users here
  scope "/", MangoWeb do
    pipe_through [:browser, :frontend, MangoWeb.Plugs.AuthenticateUser]

    get "/logout", SessionController, :delete
    get "/checkout", CheckoutController, :edit
    put "/checkout", CheckoutController, :update
    get "/orders", OrderController, :index
    get "/orders/:id", OrderController, :show

    resources "/tickets", TicketController, except: [:edit, :update, :delete]
  end

  scope "/admin", MangoWeb.Admin, as: :admin do
    pipe_through [:browser, :admin]

    get "/login", SessionController, :new
    post "/sendlink", SessionController, :send_link
    get "/sendlink", SessionController, :create
  end

  scope "/admin", MangoWeb.Admin, as: :admin do
    pipe_through [:browser, :admin, MangoWeb.Plugs.RequireAdminAuth]

    resources "/users", UserController
    get "/logout", SessionController, :delete
  end

  # Other scopes may use custom stacks.
  # scope "/api", MangoWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: MangoWeb.Telemetry
    end
  end
end

lib/mango_web/views/layout_view.ex
defmodule MangoWeb.LayoutView do
  use MangoWeb, :view
  import MangoWeb.CartView, only: [cart_count: 1]

  def cart_link_text(conn = %Plug.Conn{}) do
    raw("""
    <span class="cart-count">
      "My Cart (#{cart_count(conn)})"
    </span>
    """)
  end

  def get_active_locale_class(locale) do
    if Gettext.get_locale(MangoWeb.Gettext) == locale, do: "active"
  end
end

lib/mango_web/templates/layout/admin_app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Mango Admin</title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
  </head>
  <body>
    <%= render "admin_app_nav.html", conn: @conn %>
    <div class="container">
      <%= if get_flash(@conn, :info) do %>
        <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <% end %>
      <%= if get_flash(@conn, :error) do %>
        <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
      <% end %>
      <main role="main">
        <%= @inner_content %>
      </main>
    </div>
    <script defer type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

lib/mango_web/templates/layout/admin_app_nav.html.eex
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#admin-nav">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#"><img src="<%= Routes.static_path(@conn, "/images/logo.png") %>"/> Mango Admin</a>
    </div>
    <div class="collapse navbar-collapse" id="admin-nav">
      <ul class="nav navbar-nav">
        <li><%= link "Admin Users", to: Routes.admin_user_path(@conn, :index) %></li>
        <li><%= link "Logout", to: Routes.admin_session_path(@conn, :delete) %></li>
      </ul>
    </div>
  </div>
</nav>

lib/mango_web/templates/layout/admin_login.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Mango Admin - Login</title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
  </head>
  <body>
    <div class="container">
      <%= if get_flash(@conn, :info) do %>
        <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <% end %>
      <%= if get_flash(@conn, :error) do %>
        <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
      <% end %>
      <main role="main">
        <%= @inner_content %>
      </main>
    </div>
    <script defer
            type="text/javascript"
            src="<%= Routes.static_path(@conn, "/js/app.js") %>">
    </script>
  </body>
</html>

lib/mango_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Mango · Phoenix Framework</title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
  </head>
  <body>
    <%= render "app_nav.html", conn: @conn, customer: @current_customer %>
    <div class="container">
      <%= if get_flash(@conn, :info) do %>
        <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <% end %>
      <%= if get_flash(@conn, :error) do %>
        <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
      <% end %>
      <main role="main">
        <%= @inner_content %>
      </main>
    </div>
    <script defer type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

lib/mango_web/templates/layout/app_nav.html.eex
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#primary-nav">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">
        <img src="/images/logo.png"/> Mango
      </a>
    </div>
    <div class="collapse navbar-collapse" id="primary-nav">

      <ul class="nav navbar-nav navbar-right">
        <li><%= link cart_link_text(@conn), to: Routes.cart_path(@conn, :show), class: "cart nav-link" %></li>
        <%= if @customer do %>
          <li><%= link "My Orders", to: Routes.order_path(@conn, :index) %></li>
          <li><%= link "Log Out", to: Routes.session_path(@conn, :delete) %></li>
        <% else %>
          <li><%= link "Register", to: Routes.registration_path(@conn, :new), class: "nav-link" %></li>
          <li><%= link "Sign in", to: Routes.session_path(@conn, :new), class: "nav-link" %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

<ul style="display: flex; gap: 12px;">
  <li class="<%= get_active_locale_class("en") %>">
    <a href="?locale=en">English</a>
  </li>
  <li class="<%= get_active_locale_class("pr_br") %>">
    <a href="?locale=pt_br">Português</a>
  </li>
</ul>